import random as r
import maker as m
import ohmy as h
bday = h.delta.days
def w():
    x = r.randint(3,23)
    char = r.choice('qwertyuiopasdfghjklzxcvbnm')
    return m.wordBuilder(char,x)
nm = input('Enable nice mode? Y/N: ').lower()
if 'y' in nm:
    nm = True
else:
    nm = False
insults = [
    'This is why people talk about you when you\'re not around.',
    'Ur mom.',
    'no u.',
    'You\'re two letters short of an asset.',
    'Honey, you aren\'t pretty enough to be this stupid.',
    'You\'re so inbred that your family tree is a 2x4.',
    'I don\'t have the time or the crayons to explain this to you.',
    'I was in English class one day, and we were studying Romeo and Juliet.\nHe said, "Most people don\'t understand what a tragedy really is.\n\
    A tragedy is when there is hope, until the end, where it is all taken away."\n  That reminds me of you.',
    'You have a face for radio...\nand a voice for print.',
    'I envy people that never met you.',
    "You’re as bright as a black hole and twice as dense.",
    'You hit like a vegetarian.',
    'You\'ll never be half the man your mother is.',
    'I diagnose you with the big gay.',
    'I was pro-life before I met you.',
    'Your IQ wouldn\'t make a respectable earthquake.',
    'It\'s nice to see you\'ve reached your full potential.',
    'If you want to hurt yourself, just climb up to your ego and jump down to your IQ.',
    '"Ew."',
    "You're the human equivalent of a participation trophy.",
    'Somewhere out there is a tree, working very hard to replace the oxygen you are wasting.',
    'The only way you could be a bigger idiot is if you were taller.',
    'Your mother was a hamster and your father smelled of elderberries.',
    'In a battle of wits, clearly you are unarmed.',
    'You\'ve got something on your chin.\n\
    No not that one, the third one.',
    'I hope you outlive your children.',
    'May both sides of your pillow always be warm.',
    'Your grades say marry rich, your face says study harder.',
    "It's rude enough being alive when no one wants you.",
    "Everyone who has ever left you was right.",
    "It's impossible to underestimate you.",
    "You continue to meet my expectations.",
    'You\'re so ugly, you couldn\'t even arouse suspicion.',
    "May you search for your children with a Geiger Counter.",
    'You smell like ham... I hate ham.',
    'You couldn\'t pour water out of a boot if the instructions were on the heel.',
    'Nice moves, you wet brick.',
    'Ha, nerd.',
    'You can\'t play hard to get if you\'re hard to want.',
    'Your face looks like something I\'d draw with my left hand.',
    'Villain, I have done thy mother.',
    'Hulkamania is like a single grain of sand in the Sahara desert that is Nacho Madness.',
    'People just tolerate you.',
    'You look like you smell like cheese.',
    'Your parents are brothers.',
    "It looks like your face caught fire, and someone put it out with a fork.",
    'You have all the virtues I dislike and none of the vices I admire.',
    'I won\'t attend your funeral, but I\'ll send a nice letter saying I approve of it.',
    "I'd be surprised if you can count to 20 with your shoes on.",
    "You may be slow, but at least everything you do is wrong.",
    'How is your wife and my kids?',
    'You\'re not the dumbest guy in the room, but you\'d better hope he doesn\'t die.',
    'Thou\'st moves butter no parsnips.',
    'I bite my thumb at thee.',
    'Chump.',
    'Dunce.',
    'Clown.',
    'You, sir, are not a gentleman.',
    'Jabroni.',
    'Milk drinker.',
    'I push out two players just like you, every morning, in the toilet.',
    'Make me.',
    'Woah.',
    'Gnarly.',
    'You are a%s.'%r.choice([' table', ' chair', ' lamp', ' sink', 'n octagon', ' tetrahedron', ' whore', 'n mountain', ' hunk', ' comma', ' pie', ' keyboard', ' cheese', ' wombat']),
    'ive done ur mom.',
    'Nice move, bro.',
    'Fistbump.',
    'oh god oh fuck',
    '???????????',
    '%s %s %s, %s %s %s %s, %s %s %s %s!'%(w(),w(),w(),w(),w(),w(),w(),w(),w(),w(),w()),
    'Your moves taste like fermented cow.',
    'Compare your life to mine and then kill yourself.',
    'You\'re your own grandfather!',
    'Yo mama so %s, she can\'t even %s.'%(w(),w()),
    '%s chewer.'%w(),
    'Hey, did you know that Hitler is %s days old? Wow!'%bday
    ]
if nm:
    insults = [
        'You look nice today.',
        'If everyone was like you, there would be no need for heaven. We\'d already be there.',
        'Have you been working out? You look amazing!',
        'Is that a new shirt? It\'s very nice.',
        'Wow!',
        'I wish I was as smart as you!',
        'You\'re so smart!',
        'Nice moves, bro.',
        'Oh, nice!',
        'I never would have thought of that.',
        'Did you go to Harvard?',
        'eef freef',
        'Your mother is a nice lady.',
        'You are an asset to society.',
        'Mufufu!',
        'You have impeccable manners',
        ':)',
        'I love you.',
        'You\'re precious.',
        'What a fine chap you are.',
        'You are my son now.',
        'Happy birthday!',
        'Beautiful.',
        'What a nice face you have.',
        'Being around you makes everything better!',
        'When you say, "I meant to do that," I totally believe you.',
        'Jokes are funnier when you tell them.',
        'You should be thanked more often. So thank you!!',
        'You have cute elbows. For reals!',
        "When I'm down you always say something encouraging to help me feel better.",
        'You help me be the best version of myself.',
        "You're always learning new things and trying to better yourself, which is awesome.",
        'You could survive a Zombie apocalypse.',
        'Your voice is magnificent.',
        'The people you love are lucky to have you in their lives.',
        "You're like a breath of fresh air.",
        'You make my insides jump around in the best way.',
        "There's ordinary, and then there's you.",
        "You're someone's reason to smile.",
        "You're even better than a unicorn, because you're real.",
        'How do you keep being so funny and making everyone laugh?',
        'You have a good head on your shoulders.',
        'Has anyone ever told you that you have great posture?',
        'The way you treasure your loved ones is incredible.',
        "You're really something special.",
        'Thank you for being you.',
        'You are really courageous.',
        'Your kindness is a balm to all who encounter it.',
        "On a scale from 1 to 10, you're an 11.",
        "You've got an awesome sense of humor!",
        'You are really courageous.',
        'Your kindness is a balm to all who encounter it.',
        "You're all that and a super-size bag of chips.",
        'You are strong.',
        "You're even more beautiful on the inside than you are on the outside.",
        "I'm inspired by you.",
        "You're like a ray of sunshine on a really dreary day.",
        'You are making a difference.',
        'Thank you for being there for me.',
        "You're a smart cookie.",
        'You have impeccable manners.',
        'You have the best laugh.',
        'I appreciate you.',
        'You are the most perfect you there is.',
        'You are enough.',
        "You're strong.",
        "Your perspective is refreshing.",
        "I'm grateful to know you.",
        'You light up the room.',
        'You deserve a hug right now.',
        'You should be proud of yourself.',
        "You're more helpful than you realize.",
        'You have a great sense of humor.',
        "You've got an awesome sense of humor!",
        "You are really courageous.",
        'Your kindness is a balm to all who encounter it.',
        'You were cool way before hipsters were cool.',
        'That color is perfect on you.',
        'Hanging out with you is always a blast.',
        'You help me feel more joy in life.',
        'Being around you makes everything better!',
        "Colors seem brighter when you're around.",
        "You're better than a triple-scoop ice cream cone. With sprinkles.",
        ]
